# xp-framework/rest

language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - wget 'https://github.com/xp-framework/xp-runners/releases/download/v6.3.0/setup' -O - | php
  - composer install --prefer-dist

script:
  - USE_XP=vendor/xp-framework/core ./unittest src/test/php
